[program:html-to-pdf-flask]
command=<path to virtualenv>/bin/uwsgi --ini uwsgi.ini
directory=<path to pdf service>
stopsignal=QUIT
stdout_logfile=/tmp/html-to-pdf-flask_log.log
stderr_logfile=/tmp/html-to-pdf-flask.log
autorestart=true
stopasgroup=true
killasgroup=true
environment=BASE_PATH=<path to site>
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
stdout_logfile_backups=5
stderr_logfile_backups=5
